### ISSUE TITLE
How to: expand to see complete parameter

### ISSUE THREAD

**Issue by helphelpplease** [alexmojaki/snoop#47] opened 2021-11-05 21:07 UTC
Hi, thankyou for snoop and depth setting. Super helpful.is there a setting that allows me to see entire parameter/ variable ?

For example : DeviceId='9...
deviceid is 128 characters and I would like to see it all.

Thankyou
Python 3.9, Mac 10.13.6

**Comment by alexmojaki** [comment] 2021-11-05 21:10
Duplicate of https://github.com/alexmojaki/snoop/issues/26

**Closed by alexmojaki** 2021-11-05 21:10 UTC
